spring.banner.location=${spring.config.location:classpath:}banner.txt
spring.application.name=ms-sat-web-api
spring.main.allow-bean-definition-overriding=true
spring.profiles.include=errors
spring.profiles.active=dev
spring.threads.virtual.enabled=true
server.servlet.context-path=/sat-web-api
path.base.front=http://localhost:4200
######################################################## LOGS #############################################
logging.level.org.hibernate.SQL=ERROR
logging.level.com.zaxxer.hikari.HikariConfig=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
logging.file.name=/opt/log/sat/logs/sat-api.log
logging.file.path=/opt/log/sat/logs/

######################################################## MESSAGE GLOBAL #############################################
message.global.save=Se ha registrado de forma correcta
message.global.update=Se actualizo de forma correcta
message.global.delete=Se dio de baja de forma correcta
message.global.alta=Se dio de alta de forma correcta
message.global.update.password=Su contraseña ha sido cambiada exitosamente
message.global.reset.password=Su contraseña ha sido reseteada exitosamente. Verifique el correo electronico asociado para continuar con el poceso

email.template.registro.usuario=templates/email/registro-usuario.vm
email.template.registro.administrador=templates/email/registro-administrador.vm
email.template.forgot.password=templates/email/forgot-password.vm
email.template.change.password=templates/email/change-password.vm
email.template.match.solicitud=templates/email/match-solicitud.vm
email.template.match.confirmar=templates/email/match-confirmar.vm
